version: '3.4'

services:
  helios.ecrf:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=3300
      - ASPNETCORE_HTTPS_PORTS=3301
    ports:
      - "3300"
      - "3301"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
  # helios.authentication:
  #   environment:
  #     - ASPNETCORE_ENVIRONMENT=Development
  #   ports:
  #       - "8080:8080"
  #       - "8081:8081"
  #   volumes:
  #     - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
  #     - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro

  # helios.core:
  #   environment:
  #     - ASPNETCORE_ENVIRONMENT=Development
  #   ports:
  #     - "3500:8080"
  #     - "3501:3501"


networks:
  v3network:
     name: v3network